appleboy/gorush

- main.go
- notification.go
- version.go
> fix #3 add server version on header.

- notification.go
https://developers.google.com/cloud-messaging/http-server-ref
> fix #1 support android notification.

- .gitignore
- Makefile
- docker/Dockerfile.build
> support linux and windows bin files.

- .gitignore
- config/apns.yaml
- gopush/config.go
- gopush/server.go
> fix #15 support ssl server.

- .gitignore
- .travis.yml
> fix testing script.

- gopush.go
- gopush/config.go
- gopush/notification.go
- gopush/notification_test.go
> Fix #22 Add check android and ios conf.

- gopush/notification.go
- gopush/notification_test.go
- gopush/server_test.go
> support go goroutines.

- .gitignore
- config/config.yaml
- gopush.go
- gopush/config.go
- gopush/global.go
- gopush/log.go
- gopush/log_test.go
> Fix #25 support log.

- .gitignore
- README.md
- config/config.yaml
- gopush/config.go
- gopush/const.go
- gopush/log.go
- gopush/log_test.go
- gopush/notification.go
- gopush/notification_test.go
- gopush/server.go
- gopush/server_test.go
> Fix #29 Add request and response log

- gopush/notification.go
- gopush/notification_test.go
> fix #31 support iOS expiration field

- README.md
- gopush/notification.go
- gopush/notification_test.go
- gopush/server_test.go
> fix #32 support  overwrite android api key from post field.

- Makefile
- docker/Dockerfile.testing
> #10 support testing in docker.

- .travis.yml
- README.md
- gopush/server.go
> fix #44 Support Zero downtime restarts for go servers

- README.md
- gopush/notification.go
- gopush/notification_test.go
- gopush/server.go
> Fix #46 Enhance document and android payload

- Makefile
- doc.go
- gopush.go
- gopush/config.go
- gopush/const.go
- gopush/global.go
- gopush/log.go
- gopush/notification.go
- gopush/notification_test.go
- gopush/server.go
- gopush/server_test.go
- gopush/version.go
> fix #48 golint error.

- README.md
- config/config.yml
- gorush/config.go
- gorush/const.go
- gorush/server.go
- gorush/server_test.go
> fix #56 show server yml config file.

- gorush/const.go
- gorush/status.go
- gorush/storage/redis/redis.go
- gorush/storage/redis/redis_test.go
> Fixed #67 Support redis interface.

- gorush/storage/boltdb/boltdb.go
- gorush/storage/boltdb/boltdb_test.go
> Fixed #70 Support boltDB interface.

- Makefile
- docker/Dockerfile.testing
- docker/docker-compose.testing.yml
> Fixed #82 Support docker compose for concurrent build.

- README.md
- config/config.go
- config/config.yml
- gorush/log.go
- gorush/log_test.go
> Fixed #85 Add hideToken func.

- docker/docker-compose.testing.yml
- docker/golang/Dockerfile
- docker/testing.sh
> replace go path with global variable.

- README.md
- gorush.go
> Add command usage.

- README.md
- config/config.go
- config/config.yml
- gorush.go
- gorush/notification.go
- gorush/notification_test.go
> fixed #90 Support load p12 format of certificate file.

- README.md
- config/config.go
- config/config.yml
- config/config_test.go
- glide.lock
- glide.yaml
- gorush/server.go
- gorush/server_test.go
- gorush/status.go
https://github.com/thoas/stats
Fixed #103
> Show response time, status code etc.

- .travis.yml
- Makefile
- go.test.sh
- storage/memory/memory_test.go
> Support testing multiple package in subfolder.

- README.md
- config/config.go
- config/config.yml
- config/config_test.go
- gorush.go
- gorush/notification.go
- gorush/notification_test.go
> Support HTTP Proxy for GCM

- docker/Dockerfile.build
> fix docker build error.

- Makefile
- README.md
- config/config.go
- config/config.yml
- config/config_test.go
- glide.lock
- glide.yaml
- storage/buntdb/buntdb.go
- storage/buntdb/buntdb_test.go
> Support BuntDB engine.

- .travis.yml
- Makefile
- docker/Dockerfile.build
- docker/Dockerfile.dist
- script/build.sh
> Support scratch container.

- README.md
- config/config.go
- config/config.yml
- config/config_test.go
- gorush.go
> Support PID file

- config/config.go
- config/config_test.go
- gorush.go
- gorush/notification.go
- gorush/notification_test.go
- gorush/server.go
- gorush/server_test.go
> changed type for core section.

- .travis.yml
> Support go version 1.7.1

- .gitignore
- Makefile
- config/config.go
- config/config.yml
- config/config_test.go
- glide.lock
- glide.yaml
- gorush/status.go
- gorush/status_test.go
- storage/leveldb/leveldb.go
- storage/leveldb/leveldb_test.go
- storage/redis/redis.go
> support LevelDB key/value database.

- README.md
- config/config.go
- config/config.yml
- config/config_test.go
- gorush/notification.go
> Support retry send notification if server response is fail.

- gorush/notification.go
- gorush/notification_test.go
> Suppo zero value to clear the badge on the app icon.

- gorush/notification.go
- gorush/notification_test.go
> fixed #147 support zero value of badge.

- gorush/notification.go
- gorush/notification_test.go
> ignore alert object if message is empty.

- Makefile
- glide.lock
- glide.yaml
- gorush/server.go
Fixed #158 
https://github.com/fvbock/endless/pull/19
> Support Windows binary.

- glide.lock
- glide.yaml
- gorush/log.go
fixed #160 
ref: https://github.com/gin-gonic/gin/pull/754
> skip ANSI color commands

- README.md
- glide.lock
- glide.yaml
- gorush/server_test.go
- gorush/server_unix.go
- storage/redis/redis.go
Fix #165 and also fix https://github.com/appleboy/gorush/issues/143
> replace endless with facebook grace package.

- config/config.go
- config/config.yml
- config/config_test.go
- glide.lock
- glide.yaml
- gorush/metrics.go
- gorush/server.go
- gorush/server_test.go
- gorush/status_test.go
> feat: support prometheus metric url.

- main.go
> feat: support title flag on cli

- README.md
- config/config.go
- config/config.yml
- config/config_test.go
> feat: set runtime.NumCPU() as default worker num value

- README.md
- gorush/notification.go
- gorush/notification_test.go
> feat: Add support for the mutable-content flag

- gorush/notification.go
- gorush/notification_test.go
> fix: check certificate file exist.

- contrib/init/debian/README.md
- contrib/init/debian/gorush
fix https://github.com/appleboy/gorush/issues/189
> feat: [ci skip] add debian/ubuntu init script.

- .drone.yml
- gorush/status_test.go
- storage/redis/redis_test.go
> refactor: upgrade drone to 0.6

- vendor/github.com/sideshow/apns2/README.md
- vendor/github.com/sideshow/apns2/client.go
- vendor/github.com/sideshow/apns2/client_go16.go
- vendor/github.com/sideshow/apns2/client_go17.go
- vendor/vendor.json
See the release guide: https://github.com/sideshow/apns2/releases/tag/v0.9
> feat: upgrade apns2 to v0.9

- main.go
> fix: improve cli command error.

- .drone.yml
> feat: support group build.

- Dockerfile
- Makefile
> support multi-stage docker image.

- Dockerfile
- Makefile
> Revert "support multi-stage docker image."

- main.go
> feat: support storage engine flag.

- main.go
> add redis addr flag.

- gorush/global.go
- storage/storage.go
> move storage interface to storage folder.

- vendor/github.com/gin-contrib/sse/LICENSE
- vendor/github.com/gin-contrib/sse/README.md
- vendor/github.com/gin-contrib/sse/sse-decoder.go
- vendor/github.com/gin-contrib/sse/sse-encoder.go
- vendor/github.com/gin-contrib/sse/writer.go
- vendor/github.com/gin-gonic/gin/CHANGELOG.md
- vendor/github.com/gin-gonic/gin/Makefile
- vendor/github.com/gin-gonic/gin/README.md
- vendor/github.com/gin-gonic/gin/context.go
- vendor/github.com/gin-gonic/gin/context_appengine.go
- vendor/github.com/gin-gonic/gin/deprecated.go
- vendor/github.com/gin-gonic/gin/errors.go
- vendor/github.com/gin-gonic/gin/fs.go
- vendor/github.com/gin-gonic/gin/gin.go
- vendor/github.com/gin-gonic/gin/path.go
- vendor/github.com/gin-gonic/gin/render/html.go
- vendor/github.com/gin-gonic/gin/test_helpers.go
- vendor/github.com/gin-gonic/gin/tree.go
- vendor/vendor.json
> upgrade gin to v1.2

- gorush/global.go
- gorush/notification_fcm.go
- gorush/notification_fcm_test.go
- gorush/notification_test.go
- main.go
> refactor(andorid): initial client.

- gorush/server.go
- gorush/server_test.go
> check response header.

- .drone.yml
- Dockerfile
> update docker build

- Makefile
> [ci skip] add comment on Makefile.

- config/config_test.go
- gorush/log.go
- gorush/notification_apns.go
- gorush/notification_apns_test.go
- gorush/notification_fcm.go
- gorush/notification_test.go
- gorush/status_test.go
fix lint from the tool https://github.com/alecthomas/gometalinter
> fix lint error.

- storage/boltdb/boltdb.go
- storage/boltdb/boltdb_test.go
- storage/buntdb/buntdb.go
- storage/buntdb/buntdb_test.go
- storage/leveldb/leveldb.go
- storage/leveldb/leveldb_test.go
- storage/redis/redis_test.go
> fix lint error in storage folder.

- gorush/server.go
- gorush/server_test.go
- k8s/gorush-deployment.yaml
- k8s/gorush-service.yaml
> add healthz check

- gorush/server.go
- gorush/server_test.go
> add version handler

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
- README.md
- config/config.go
- config/config.yml
- config/config_test.go
- rpc/example/go/client.go
- rpc/example/node/client.js
- rpc/server.go
> change grpc port to 9000

- Dockerfile
- Dockerfile.arm
- Dockerfile.arm64
> remove yaml config in Dockerfile.

- k8s/gorush-aws-alb-ingress.yaml
- k8s/gorush-configmap.yaml
- k8s/gorush-deployment.yaml
> support global config in k8s.

- vendor/github.com/dgrijalva/jwt-go/LICENSE
- vendor/github.com/dgrijalva/jwt-go/MIGRATION_GUIDE.md
- vendor/github.com/dgrijalva/jwt-go/README.md
- vendor/github.com/dgrijalva/jwt-go/VERSION_HISTORY.md
- vendor/github.com/dgrijalva/jwt-go/claims.go
- vendor/github.com/dgrijalva/jwt-go/doc.go
- vendor/github.com/dgrijalva/jwt-go/ecdsa.go
- vendor/github.com/dgrijalva/jwt-go/ecdsa_utils.go
- vendor/github.com/dgrijalva/jwt-go/errors.go
- vendor/github.com/dgrijalva/jwt-go/hmac.go
- vendor/github.com/dgrijalva/jwt-go/map_claims.go
- vendor/github.com/dgrijalva/jwt-go/none.go
- vendor/github.com/dgrijalva/jwt-go/parser.go
- vendor/github.com/dgrijalva/jwt-go/rsa.go
- vendor/github.com/dgrijalva/jwt-go/rsa_pss.go
- vendor/github.com/dgrijalva/jwt-go/rsa_utils.go
- vendor/github.com/dgrijalva/jwt-go/signing_method.go
- vendor/github.com/dgrijalva/jwt-go/token.go
- vendor/github.com/sideshow/apns2/README.md
- vendor/github.com/sideshow/apns2/client.go
- vendor/github.com/sideshow/apns2/token/token.go
- vendor/vendor.json
ref: https://github.com/appleboy/gorush/issues/247
> upgrade apns2 to 0.13

- gorush/notification.go
- gorush/notification_fcm.go
- gorush/notification_test.go
- vendor/github.com/appleboy/go-fcm/response.go
- vendor/vendor.json
fix https://github.com/appleboy/gorush/issues/298
> support Device Group HTTP POST Request

- README.md
- config/config.go
- config/config.yml
- config/config_test.go
- gorush/server.go
> support custom url for health URI.

- gorush/notification.go
- gorush/notification_apns.go
- gorush/notification_apns_test.go
> Add CollapseID for ios notification.

- .appveyor.yml
- Dockerfile.windows
> feat(windows): support windows container.

- Dockerfile
- Dockerfile.alpine
- Dockerfile.arm
- Dockerfile.arm64
- Dockerfile.i386
- Dockerfile.windows
- main.go
> feat(docker): test a container to check that it is still working

- rpc/server.go
fix partial https://github.com/appleboy/gorush/issues/348
> chore: return success for rpc response.

- gorush/notification.go
- gorush/notification_apns.go
- gorush/notification_apns_test.go
- gorush/notification_fcm.go
- vendor/github.com/sideshow/apns2/README.md
- vendor/github.com/sideshow/apns2/client.go
- vendor/github.com/sideshow/apns2/client_go16.go
- vendor/github.com/sideshow/apns2/client_go17.go
- vendor/github.com/sideshow/apns2/payload/builder.go
- vendor/github.com/sideshow/apns2/response.go
- vendor/vendor.json
fix https://github.com/appleboy/gorush/issues/366
> feat(ios): Support iOS 12 Critical Alerts

- README.md
> docs(ios): Support iOS 12 Critical Alerts

- go.mod
- go.sum
- gorush/notification.go
- gorush/notification_apns.go
- gorush/notification_apns_test.go
- vendor/github.com/sideshow/apns2/payload/builder.go
- vendor/vendor.json
> feat(ios12): Add support for Summary arguments in notifications

- go.mod
- go.sum
- gorush/notification_apns.go
- gorush/notification_apns_test.go
- vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
- vendor/github.com/mitchellh/mapstructure/README.md
- vendor/github.com/mitchellh/mapstructure/decode_hooks.go
- vendor/github.com/mitchellh/mapstructure/go.mod
- vendor/github.com/mitchellh/mapstructure/mapstructure.go
- vendor/vendor.json
> fix(ios): mapstructure for sound field.

- storage/badger/badger.go
- bager rename badger
- Value method not usable, therfore changed to ValueCopy
> fixed #402 item get value error fix

- .drone.yml
- go.mod
- go.sum
- pipeline.libsonnet
> chore(drone): upgrade to go 1.13

- .drone.yml
- gorush/server.go
- gorush/server_normal.go
- pipeline.libsonnet
fix: https://github.com/appleboy/gorush/issues/432
> fix: Cannot build for aws lambda

- gorush/server_lambda.go
- gorush/server_normal.go
- gorush/server_test.go
- main.go
> feat(server): support graceful shutdown

- docker-compose.yml
- go.mod
- go.sum
- gorush/log.go
- gorush/server.go
Add zerolog for gin httpd log
fixed: https://github.com/appleboy/gorush/issues/435
> chore(log): ignore /healthz request log

- README.md
- config/config.go
- config/config_test.go
- config/testdata/config.yml
- gorush/server_normal.go
- main.go
- rpc/server.go
fixed: https://github.com/appleboy/gorush/issues/465
> chore(graceful): support custom timeout value

- gorush/notification_fcm.go
Fix https://github.com/appleboy/gorush/issues/458
I think we must write unit tests for function GetAndroidNotification
> fix fcm notification

- rpc/server.go
- rpc/server_test.go
Change HTTP/1.1 server to gRPC.
> solve https://github.com/appleboy/gorush/issues/476

- go.mod
- go.sum
- storage/badger/badger.go
See: https://github.com/dgraph-io/badger/blob/master/README.md#i-see-manifest-has-unsupported-version-x-we-support-y-error
> chore(storage): upgrade badger to v2

- README.md
- config/config.go
- config/config_test.go
- config/testdata/config.yml
- storage/badger/badger.go
> chore(storage): support set db path for badger driver

- .appveyor.yml
- docker/Dockerfile.windows.amd64
- main.go
- storage/badger/badger.go
- storage/badger/badger_test.go
- storage/boltdb/boltdb.go
- storage/boltdb/boltdb_test.go
- storage/buntdb/buntdb.go
- storage/buntdb/buntdb_test.go
- storage/leveldb/leveldb.go
- storage/leveldb/leveldb_test.go
- storage/memory/memory.go
- storage/memory/memory_test.go
- storage/redis/redis.go
- storage/redis/redis_test.go
- storage/storage.go
close storage connection before shutdown the service
fix https://github.com/appleboy/gorush/issues/393
> chore(storage): storage performance issues

- go.mod
- go.sum
- storage/redis/redis.go
> chore(storage): upgrade redis to v7

- gorush/notification_apns.go
- gorush/notification_fcm.go
Check response before retry send pushes
fix #420
> Check status of response before retry send push

- .gitignore
- README.md
- contrib/init/debian/README.md
Fix path to default config in Readme's
> fix config path in readme #514

- gorush/server_test.go
> chore(server): add testing with healthz router.

- gorush/notification_apns.go
fixed https://github.com/appleboy/gorush/issues/530
> fix: check response is nil or not

- .appveyor.yml
fixed https://github.com/appleboy/gorush/issues/508
> chore(windows): Disable CGO_ENABLED

- README.md
> Revert "chore(README): use apikey for v1.13.0 or below"

- README.md
- main.go
> fix: redefined -v flag

- docker/Dockerfile.linux.amd64
- docker/Dockerfile.linux.arm
- docker/Dockerfile.linux.arm64
- docker/Dockerfile.windows.amd64
> chore: update period to one second

- core/core.go
- gorush/const.go
- gorush/feedback.go
- gorush/feedback_test.go
- gorush/global.go
- gorush/main_test.go
- gorush/notification.go
- gorush/notification_apns.go
- gorush/notification_apns_test.go
- gorush/notification_fcm.go
- gorush/notification_fcm_test.go
- gorush/notification_hms.go
- gorush/notification_test.go
- gorush/server.go
- gorush/server_normal.go
- gorush/server_test.go
- gorush/status.go
- gorush/worker.go
- logx/log.go
- logx/log_test.go
- main.go
- rpc/server.go
- rpc/server_test.go
1. move log package from gorush
2. create core package.
> refactor: create logx package

- README.md
- config/config.go
- config/testdata/config.yml
> chore: disabled Huawei notification by default

- gorush/notification.go
- gorush/notification_apns.go
- gorush/notification_apns_test.go
- gorush/notification_fcm.go
- gorush/notification_fcm_test.go
- gorush/notification_hms.go
- main.go
- queue/queue.go
- queue/simple/simple.go
- queue/worker.go
- router/server.go
- router/server_test.go
- rpc/server.go
> Only initial MaxConcurrentIOSPushes once.

- main.go
- queue/queue.go
- queue/simple/simple.go
- queue/worker.go
- router/server.go
- router/server_test.go
> chore: update worker interface

- main.go
- queue/simple/simple.go
- router/server_test.go
> chore(queue): support option setting

- queue/queue.go
- queue/simple/simple.go
- queue/simple/simple_test.go
> chore(queue): to handle panic cases from inside the worker

- helm/gorush/Chart.yaml
> chore(helm): update app version to 1.14.0

- go.mod
- gorush/feedback.go
- gorush/notification.go
- gorush/notification_apns_test.go
- gorush/notification_hms.go
> chore(notification): Support Bytes for message queue

- README.md
- config/config.go
- config/config_test.go
- config/testdata/config.yml
- core/queue.go
- go.mod
- go.sum
- gorush/notification_apns.go
- gorush/notification_fcm.go
- gorush/notification_hms.go
- main.go
- queue/nsq/nsq.go
- queue/queue.go
- queue/simple/simple.go
- queue/simple/simple_test.go
- queue/worker.go
- router/server.go
- status/status.go
ref: #599 
Support NSQ as backend. `Sync` mode only working for local Queue.
Please check the following config:
```yaml
queue:
engine: "local" # support "local", "nsq", default value is "local"
nsq:
addr: 127.0.0.1:4150
topic: gorush
channel: ch
```
> chore(queue): support NSQ as backend.

- .drone.yml
- .gitignore
- pipeline.libsonnet
- queue/nsq/nsq.go
- queue/nsq/nsq_test.go
- queue/queue.go
> fix(NSQ): close service after waiting all job completed.

- gorush/notification.go
- queue/nsq/nsq.go
- queue/queue.go
- queue/simple/simple.go
- queue/simple/simple_test.go
- queue/worker.go
- router/server.go
- rpc/server.go
> chore(queue): add queue message interface

- main.go
- queue/simple/simple.go
> chore(queue): support custom run func

- queue/nsq/nsq.go
- queue/nsq/nsq_test.go
> chore(NSQ): support custom run func and maxInFlight flag

- queue/simple/simple.go
- queue/simple/simple_test.go
> refactor(queue): update run func in simple channel

- gorush/main_test.go
- logx/log.go
- queue/nsq/README.md
- queue/nsq/nsq_test.go
- queue/simple/simple_test.go
- router/server_test.go
- rpc/server_test.go
- status/status_test.go
> chore: init log package

- queue/logger.go
- queue/queue.go
ref: #599 
Add default logger interface
> chore: support custom logger in queue package

- main.go
- queue/nsq/nsq_test.go
- queue/queue.go
- queue/simple/simple_test.go
- router/server_test.go
> chore: support custom parameter in queue

- Makefile
- main.go
- notify/feedback.go
- notify/feedback_test.go
- notify/global.go
- notify/main_test.go
- notify/notification.go
- notify/notification_apns.go
- notify/notification_apns_test.go
- notify/notification_fcm.go
- notify/notification_fcm_test.go
- notify/notification_hms.go
- notify/notification_hms_test.go
- notify/notification_test.go
- queue/nsq/nsq.go
- queue/simple/simple.go
- queue/simple/simple_test.go
- router/server.go
- router/server_test.go
- rpc/server.go
> chore: rename gorush to notify package

- queue/nsq/nsq_test.go
- queue/queue.go
- queue/simple/simple_test.go
> chore(queue): Shutdown service once.

- queue/queue.go
- queue/simple/simple_test.go
> chore(queue): returns the numbers of workers has been created

- go.mod
- go.sum
- main.go
- notify/notification.go
ref: https://github.com/appleboy/queue/pull/6 and #599 
> chore(NSQ): remove nsq package and update run func

- go.mod
- go.sum
- logx/log.go
- notify/notification.go
- notify/notification_apns.go
- notify/notification_fcm.go
- notify/notification_fcm_test.go
- notify/notification_hms.go
- router/server.go
- router/server_test.go
ref: https://github.com/appleboy/gorush/issues/599
> chore(queue): upgrade appleboy/queue to 0.5.0

- main.go
- notify/notification.go
- notify/notification_apns.go
- notify/notification_apns_test.go
- notify/notification_fcm.go
- notify/notification_fcm_test.go
- notify/notification_hms.go
- router/server.go
- router/server_test.go
- rpc/server.go
> refactor: remove config from notification struct.

- README.md
- config/config.go
- config/config_test.go
- config/testdata/config.yml
- go.sum
- main.go
> chore(queue): Support NATS as backend

- go.mod
- go.sum
> fix(hms): refresh token fail

- notify/notification.go
- notify/notification_apns.go
- notify/notification_fcm.go
- notify/notification_hms.go
move the process of send error to specific URL.
> chore(push): send error to specific URL

- .drone.yml
- logx/log.go
- main.go
- notify/main_test.go
- notify/notification_apns_test.go
- notify/notification_fcm_test.go
- pipeline.libsonnet
- router/server.go
- router/server_normal.go
- router/server_test.go
- rpc/client_grpc_health.go
- rpc/example/go/health/main.go
- rpc/server.go
- status/status_test.go
- storage/badger/badger.go
> fix: error from golangci-lint tool

- README.md
- notify/notification_apns.go
- notify/notification_apns_test.go
- notify/notification_fcm.go
- notify/notification_hms.go
- router/server.go
- router/server_test.go
- rpc/example/go/send/main.go
> chore(lint): fix some condition.

- notify/feedback.go
- notify/notification.go
- notify/notification_apns.go
- notify/notification_apns_test.go
> chore: fix some lint

- logx/log_interface.go
- main.go
- router/server_test.go
> chore(logx): add custom logger in queue

- logx/log.go
- logx/log_test.go
> fix token don't send on feedback

- .drone.yml
- pipeline.libsonnet
> chore: upgrade golang to 1.17

- go.mod
- go.sum
- main.go
> chore(service): add graceful shutdown.

- go.mod
- go.sum
- rpc/server.go
fix https://github.com/appleboy/gorush/issues/691
Signed-off-by: Bo-Yi.Wu <appleboy.tw@gmail.com>
> chore(gRPC): a new unary server interceptor for panic recovery

- .gitignore
- notify/feedback.go
> fix #751: Use one http.Client instance for feedback callbacks

- rpc/server.go
Enable TLS for gRPC if SSL is set to true and cert/key is specified.
> feat(grpc): add TLS support 

- notify/notification_fcm.go
fixed #784 
@appleboy this is important PR, in our company a lot of crashed push messages.
> fix(fcm): nested data in input message

- router/server_normal.go
- Remove nolint comment
- Update minimum TLS version from 1.0 to 1.2
fix #792
> chore(httpd): enhance security and testing protocols
